'use strict'

module.exports = {
    jwt: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmNlMTcyNjM3NWE1MWRiNjRkNWUxOGMiLCJlbWFpbCI6ImNhaW8ubWFqZGFsYW5pQGdtYWlsLmNvbSIsImlhdCI6MTU0ODE3MzEzNX0.exjyVRCE2e9BsnlShLVa7cxfHsWEoBxQ2YRpJiAypAA'
}